export const GET_CASEONE_OFFER = "GET_CASEONE_OFFER";
export const CASEONE_ERROR = "CASEONE_ERROR";
export const GET_CASETWO_OFFER = "GET_CASETWO_OFFER";
export const CASETWO_ERROR = "CASETWO_ERROR";
export const DELETE_OFFER = "DELETE_OFFER";
export const GET_CASETHREE_OFFER = "GET_CASETHREE_OFFER";
export const CASETHREE_ERROR = "CASETHREE_ERROR";
