export const GET_CASE_ONE_OFFER_LİST = "GET_CASE_ONE_OFFER_LİST";
export const CASE_ONE_ERROR = "CASE_ONE_ERROR";
export const GET_CASE_TWO_OFFER_LİST = "GET_CASE_TWO_OFFER_LİST";
export const CASE_TWO_ERROR = "CASE_TWO_ERROR";
export const DELETE_CASE_THREE_OFFER_LİST = "DELETE_CASE_THREE_OFFER_LİST";
export const GET_CASE_THREE_OFFER_LİST = "GET_CASE_THREE_OFFER_LİST";
export const CASE_THREE_ERROR = "CASE_THREE_ERROR";
